name: Master
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:
    name: Install, build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm start